require("configs/packer")
require("nvimutils")
require("settings")
require("keymappings")
require("configs/telescope")
require("configs/complete")
require("configs/mason")
require("configs/workspaces")
